[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=100
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-0]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9000 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-1]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9001 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-2]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9002 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-3]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9003 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-4]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9004 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-5]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9005 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-6]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9006 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-backend-7]
command=/usr/local/bin/php -d upload_max_filesize=100M -d post_max_size=110M -d opcache.enable_cli=1 -S 127.0.0.1:9007 -t /app
autorestart=true
priority=200
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
